name: Transformer-Model
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13.12
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - torch
  - scikit-learn
  - PyWavelets
  - jupyterlab
  - notebook
  - pip
